[[architecture]]
==== Architecture

[[product-architecture]]
===== Product Context

_Product Architecture_ is the arrangement of functional elements into physical chunks which become the building blocks for the product or family of products. Architecture decisions determine how to divide a product or product family into chunks, how to assign functional elements to chunks and how much modularity to impose.

footnote:["Product Design and Development" by Ulrich, Karl T, Eppinger, Steven D and Yang, Maria  C., McGraw-Hill Higher Education. 7th Edition, ISBN 978-1-260-04365-5]

[[system-architecture]]
===== System Engineering Context

System architecture is the embodiment of concept, the allocation of physical/informational  function to the elements of form, and the definition of relationships among the elements  and with the surrounding context. 

footnote:["System Architecture" by Cameron, Bruce, Crawley, Edward Selva and Daniel, Global Edition. Pearson Education Limited. ISBN 10: 1-292-11084-8]

[[software-architecture]]
===== ISO/IEC/IEEE Context

Architecture is the fundamental organization of a system, embodied in its components, their relationships to each other and to the environment, and the principles governing its design and  evolution. 

footnote:[ISO/IEC/IEEE Standard 42010]


