[[problem-discovery]]
=== Problem Discovery

In his book _"Kaizen and the art of creative thinking"_ Shigeo Shingo footnote:[pcspress.com, 2007, translated by Enna Products Corporation and PCS Inc., ISBN 978-1-897363-59-1] states there are three essential steps to problem solving:

* Find the problem
* Clarify the problem
* Find the cause.

Finding the right problems is the a critical first step that is too often skipped. Engineers and architects are by training proficient problem solvers. What happens when they do not even realize a problem exists, or when they misunderstand the nature of the problem altogether?

In his book _"What's your problem? To solve your toughest problems, change the problems you solve"_ Thomas Wedell-Wedellsborg footnote:[Harvard Business Review Press, 2020, ISBN 9781633697225] asks a challenging question: are you solving the right problems? *Problem Discovery* aims at helping agile teams find the right problems and better frame them.

==== Find the right problems

Challenging the status quo helps surface new problems the enterprise must address to improve. Actors in the enterprise too often base their decisions and actions on assumptions they think are true but are not. When decisions and actions are based on unverified assumptions, the risk of unintended outcomes is high. When facts are not established, the reasoning that link countermeasures to expected improvements is likely to be flawed. Knowing what you don't know is critical.

In her book _"The pyramid principle: logic in writing and thinking_" footnote[Pearson Education Limited, 2009, ISBN: 978-0-273-71051-6], Barbara Minto writes: _"When you identify a problem, essentially what you do is recognize that a particular situation yields a specific result. The problem is either that you do not like the result, or that you cannot explain the result"_.

Alongside with Barbara Minto, we recommend you start by creating a useful structure of the situation. In a VUCA environment, causal relationships are not likely to be linear and simple. This is why we think the best way to represent a situation is to create a systems view of the enterprise. The book _"The fith discipline fieldbook"_ includes a section, _"Starting with storytelling_" which provides a simple way to model a systems view of an organization. A good system thinker is someone who can see four levels operating simultaneously: events, patterns of behavior, systems and mental models:

* *Events* refer to individual events which have recently troubled the enterprise. They are symptoms of the problems you try to identify
* *Patterns of behavior* is about understanding you apparently isolated events relate to each other; the authors suggest selecting key variables and tracking them back three or four years to discover trends
* The *systemic structure* is about representing the key interrelationships that link these factors; This is an iterative process which consists in adding and removing hypothesis until you can draw a meaningful and possibly simple diagram that provides a useful representation of the system
* last level is about changing the existing *Mental Models* of the actors of the enterprise when these are based of flawed causality assumptions.

When representing a systemic structure, implicit or explicit assumptions on the boundaries of the systems are made. We'll see in the next section that changing these boundaries is key to reframing your problem.

==== Reframing problems



