[[as-is-state]]
== "As-is" State of the bank

The bank operates in three countries, France, Germany and Spain. 

In France the banks operates under three brands:

* *Universal* which caters to consumers, small businesses and enterprises through a click and mortar model with 740 branches
* *Entrepreneurs* which caters to small businesses and their owners through a network of 420 branches mainly operating in the south east part of the country
* *Direct Bank* which caters to young urban consumers through a mobile banking model.

In Germany the bank operates under the *Broker* brand and provides Personal Investment services mainly through a direct banking model with a few branches in large cities.

In Spain the bank operates under the *Banco 7* brand and caters to consumers and small businesses through a click and mortar model with 860 branches.

The table below describes the product families each brand offers to the market.

[[tbl-o-aaf-safe-concepts]]
[cols="1,2a,2a,2a,2a,2a", options="header"]
.Product offerings

|===
|*Product*
|*Universal*
|*Entrepreneur*
|*Direct Bank*
|*Broker*
|*Banco 7*

|Checking account
|X
|X
|X
|X
|X

|Consumer credit
|X
|
|X
|
|X

|Consumer credit
|X
|
|X
|
|X

|Mortgage loans
|X
|X
|X
|
|X

|Saving products
|X
|
|
|X
|X

|Brokerage services
|
|
|
|X
|

|Equipment loans
|X
|X
|
|
|X

