[[as-is-state]]
== "As-is" State of RB Bank

*RB Bank* operates in three countries, France, Germany and Spain. 

In France the banks operates under three brands:

* *Uni* which caters to consumers, small businesses and enterprises through a click and mortar model with 740 branches
* *SB* which caters to small businesses and their owners through a network of 420 branches mainly operating in the south east part of the country
* *Direct* which caters to young urban consumers through a mobile banking model.

In Germany the bank operates under the *Broker* brand and provides Personal Investment services mainly through a direct banking model with a few branches in large cities.

In Spain the bank operates under the *Banco 7* brand and caters to consumers and small businesses through a click and mortar model with 860 branches.

=== Product offerings

The table below describes the product families each brand offers to the market.

[[tbl-o-aaf-safe-concepts]]
[cols="2a,1a,1a,1a,1a,1a", options="header"]
.Product offerings

|===
|*Product*
|*Uni*
|*SB*
|*Direct*
|*Broker*
|*Banco 7*

|Checking account
|X
|X
|X
|X
|X

|Payment services
|X
|X
|X
|X
|X

|Personal credit
|X
|
|X
|
|X

|Consumer credit
|X
|
|X
|
|X

|Mortgage loans
|X
|X
|X
|
|X

|Saving products
|X
|
|
|X
|X

|Brokerage services
|
|
|
|X
|

|Equipment loans
|X
|X
|
|
|X

|P&C insurance
|X
|X
|X
|
|X

|===

=== Operating model

Each brand is a legal entity that is fully owned by the RB Bank Group and manages its balance sheet and P&L. Financial and regulatory reporting is consolidated at the group level.

Each brand manages its own information system with minimum guidance from the group.

XXX.