[[experience-objectives]]
=== Experience Objectives
//:sectnums:
//:doctype: book
//:reproducible:

//:toc: preamble
//xref:o-aaf-deployment[o-aaf-deployment-vision]

In a seminal HBR paper footnote:[Marketing Myopia by Theodore Levitt, Harvard Business Review, Best of 1960] Theodore Levitt argues that companies are overly focused on producing goods or services and don’t spend enough time understanding what customers want or need. Understanding the customer should come first, and designing the product should follow. Experience objective uses the Jobs-To-Be-Done (JTBD) approach combined with Design Thinking to capture and analyze customers' wants and needs. User research practices like defining personas through interviews, experience maps ... are especially useful here. All of this helps to understand who are your users and what are their problems and expectations.

A paper published in the Harvard Business Review footnote:[Why Do So Many Strategies Fail? Leaders focus on the parts rather than the whole by David J. Collis, hbr.org, July–August 2021] observes:

* Strategic adaptation must become an ongoing, iterative process of hypothesis, experimentation, learning, and action
* The value-creation potential of a business model should be based on making a hypothesis on what's the "job to be done" for customers

The Experience Objectives view provides a template to analyze customers' JTBD, see below:

++++
<object type="image/svg+xml" data="img/jtbd-example.svg">Your browser does not support SVGs</object>
++++


+

We recommend using Design Thinking to conduct the iterative learning process that verifies customer hypothetis though prototyping and experimentation.

link:framework.html[Return to the CAF diagram]