//:sectnums:
//:doctype: book
//:reproducible:

[[framework]]
=== Continuous Architecture Framework
_By Frédéric Lé and Jean-Pierre Le Cam_
//:toc: preamble
//xref:o-aaf-deployment[o-aaf-deployment-vision]

We build software in a continuous manner, let's adapt our architecture operating model to it. That would be the elevator pitch for our Continuous Architecture initiative. 
 
Since a decade or so, lots of new software engineering practices were introduced mainly to deliver faster our products to end users. Speed is obviously key these days but it was not the only goal of those practices: their intend was also to deliver better products that fix end user problems. If you look at it, you'll see a common pattern in many companies that deployed these different transformations like agile, lean, devops ...: architecture is a missing area. The Continuous Architecture Framework (or CAF) below is our proposal to adapt our operating model to this continuous world. It is organized into six related views as depicted in this figure.

++++
<object type="image/svg+xml" data="img/ca-framework-v08.svg">Your browser does not support SVGs</object>
++++

To navigate the framework, click on rectangles that represent framework views.

Though the CAF perspectives are related, the diagram should not be interpreted as a waterfall process model. 
The activities of the framework are executed in a continuous manner. Continuous implies here to keep a balance between intentional architecture and emergent design. It helps better manage the uncertainty and complexity that characterizes the digital journey of the enterprise.

The questions below drive the navigation between the views of the framework:

* How to decompose the enterprise?
* Can we achieve product market fit through Experience Objectives?
* Do we need to improve our operational capabilities?
* How can technology enable and augment our products and capabilities?
* How can we design a truly agile organization?

//include::experience-objectives.adoc[]
//include::product.adoc[]
//include::enterprise-decomposition.adoc[]

link:https://continuous-architecture.org/[Return to the CA Toolkit overview]
