= Organization
//:sectnums:
//:doctype: book
//:reproducible:

[[organization]]
//:toc: preamble
//xref:o-aaf-deployment[o-aaf-deployment-vision]

The Organization view maps the hierarchical decomposition of the enterprise into an organizational model. 
The figure below describes the way the CAF suggests you model your organization.

image::/assets/imgs/doc/organization.svg[600,align="left",opts=inline]

We need to complete the structural decomposition of the enterprise into Operating units:

* Vertically by defining the teams that compose Operating Units
* Horizontally (organizational dimensions) by specifying how power is allocated, which skills people need, which management systems should be deployed, what are the news ways of working, the new Beliefs, Mindset and Behavior that should become the norm

The CAF proposes content that cover each of the organizational dimensions covered, for example it describes a set of of practices and rituals.
// and it explains how to shape team topologies, see: link:./docs/practices/practices.html or link:./docs/rituals/rituals.html

The figure below presents the CAF's generic team topologies model.

image::/assets/imgs/doc/team-topologies.svg[400,align="left",opts=inline]

When shaping the structure of an organization it is important to take into account:

* The Conway law by applying the reverse Conway Maneuver
* The cognitive load and the Dunbar number which defines limits when defining the scope of responsibility and the interactions of teams


link:framework.html[Return to the CAF diagram]