= Product
//:sectnums:
//:doctype: book
//:reproducible:

[[product]]
//:toc: preamble
//xref:o-aaf-deployment[o-aaf-deployment-vision]

Defining terminology is a useful starting point when reading or writing on a subject to prevent any confusion or assumptions. We will use the term Digital Product shorten to Product for simplification purposes to refer to products delivered by an IT organization. By product we mean goods and/or services, so it can be tangible (workstation, Mobile phone, ..) or intangible (Order management system, Fleet management, collaboration suite, ...). A product that meets clients' needs as captured in the *Experience Objectives* view.

The most important consideration when defining products is to clearly articulate and understand the concept of "customer" as the products we create, manage and maintain ultimately exist to deliver essential capabilities for them. The "customer" here can be: a developer, a support analyst, an employee or a "real" customer/consumer. So in this model we will use the term end-users to refer to all kind of product's customers.

Product provides a set of services / features delivered to it's community of end-users through continuous flow of releases, during all it's life cycle, from ideation to retirement, in order to continuously deliver value and enable continuous change & agility.

It's a way of organizing IT around how Information Systems and IT technology are consumed (or the value that is perceived by stakeholders), rather than how they are produced & deliver or the functionality they offer.
Even if there is a high level of variability in defining what is a product, there are common attributes and guidlines to consider when defining what is and is not a product:

* can serve internal or external *customers*
* is clearly defined by its *business capabilities*
* delivers capabilities that customers *value*
* can be a *repeatable service*
* can be a *platform* (one sided/multi sided)
* can be bought, sold, subscribed and/or *funded*
* has *competition* and a product *lifecycle*

footnote:[source Gartner, ID:441404]

Products are materialized by one or several software and/or hardware components. It is a mistake to think that a product equals an application as defined historicaly. It could be but this is not always the true.

A product team is responsible for the product delivery, including plan build and run activities and this during the whole product lifecycle (from ideation to retirement). These teams are cross-functionnal, self-organized, have dedicated members, long-lived, co-located as far as possible. Specifically, they are cross-functionnal having all skills required to fulfill their missions with a mix of IT and business staff; they are focused on and measured by outcomes (rather than output); and they are empowered to figure out the best way to solve the problems they’ve been asked to solve.

The purpose of a product team in this sense is to solve problems in ways our end-users love, yet work for our business.

Usually a product team is a squad (5-10 people), but can be a squad of squads for big products. The size of a product team or the product's portfollio a team manage can vary during the time.

link:framework.html[Return to the CAF diagram]