==== Technology
//:sectnums:
//:doctype: book
//:reproducible:

[[Technology]]
//:toc: preamble
//xref:o-aaf-deployment[o-aaf-deployment-vision]

In his seminal article _"Why Software Is Eating The World"_ footnote:[see: https://www.wsj.com/articles/SB10001424053111903480904576512250915629460] Marc Andreessen observes Software is eating much of the value chain of industries that primarily exist in the physical world. For example in today's cars, software runs the engines, controls safety features, entertains passengers and has the ability to drive autonomously. This is why the CAF focuses on two major topics:

* Designing modular software architectures
* Symbiotic coupling of machines and humans footnote:[see: The Design of Future Things by Don Norman. ISBN: 978-0-465-00228-3]

The 2017 State of DevOps Report observes the quality of architecture correlates with fast CI/CD pipelines and more broadly with IT performance. This is in line with the 2015 DevOps report's findings which states that high-performing teams are more likely to have loosely-coupled architectures than medium and low-performing teams.

The Continuous Architecture Framework and Toolkit covers the _Domain Driven Design Strategic Patterns_ which help modularize a system based on domain modeling.

link:framework.html[Return to the CAF diagram]