source "https://rubygems.org"

gem "jekyll", "~> 4.3.3"
gem 'webrick'

group :jekyll_plugins do
  gem 'jekyll-asciidoc'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.0" if Gem.win_platform?

gem 'jekyll-postcss'
