== Terms and definitions

[[capability]]
=== capability
alt:[feature]
domain:[problem domain]
The ability to produce an outcome

[[capability]]
=== capability
domain:[problem domain]
The ability to produce an outcome


[[outcome]]
=== outcome
domain:[Product and customer experience]

Event that is a change of state of some object in the domain, that has become available due the activity of a producer for the benefit of a consumer.

[[product capability]]
=== product feature
alt:[product functionality]
alt:[product feature]
domain:[Product and customer experience]

Functional characteristic of a product.

[example]
Foreign seeds, husks, bran, sand, dust.

NOTE: It provides a factual description of capabilities offered how a product delivers its outcomes.

[[product]]
=== product
domain:[Product and customer experience]

Merchandises offered for sale. Products come in two forms:
1. Goods produced as the result of manufacturing or a
2. Services, i.e. some work done by one person or group that benefits another.

[example]

NOTE: A product always include the service of sales.

