//:sectnums:
//:doctype: book
//:reproducible:
//Comment

[[caf-messages]]
=== Develop and Operate Outstanding Digital Products with an Operating Model that works!
//:toc: preamble

Continuous Architecture (CA) offers a new frame of reference footnote:[See definition https://www.merriam-webster.com/dictionary/frame%20of%20reference] that:

* Address the specific needs of your enterprise by promoting specific organizational and architecture models
* Develop and operate products that deliver an outstanding experience by leveraging digital technology and operations footnote:[See: https://continuous-architecture.org/docs/framework/framework.html]
* Offers a truly open source license footnote:[See: https://github.com/michelin/Continuous-Architecture-Toolkit#license]

Imagine what you could invent!

link:/docs/problem-discovery/problem-discovery.html[Discovering] the problems that challenge your enterprise is the starting point of your link:/docs/start-your-journey/start-your-journey.html[Continuous Architecture journey].

The current CA version is a MVP that evolves continuously. The CA team will periodically add new content and is looking for link:https://github.com/michelin/Continuous-Architecture-Toolkit/blob/master/governance/contributing.adoc[new contributors].
